### ISSUE TITLE
Environment variable mandatory

### ISSUE THREAD

**Issue by lucasgomide** [danielfireman/temp-to-go#21]
There are some environment variable mandatory for starting web project. Most of them, shouldn't mandatory tough. I'd like to propose addition a fallback for each one env that is not really mandatory to start the application, such as `PUBLIC_HTML=/public`, `MONGODB_URI=mongodb://127.0.0.1:27017/db` and `PORT=8080`

@danielfireman What do you think ? Is it makes sense ?

**Comment by danielfireman** [comment]
Sounds great to me. Two small caveats:

* PUBLIC_HTML should default to `public` (instead of `/public`)
* We sould log the env vars? Maybe it is time to start using [kelsey's envconfig awesome lib](https://github.com/kelseyhightower/envconfig)?

**Comment by lucasgomide** [comment]
Great ideia
